name: finance_digest
description: A Great Brands Nigeria Limited Project




version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  sqflite: ^2.0.0
  path: ^1.8.0
  flutter_local_notifications: ^17.2.3
  permission_handler: ^11.0.1
  http: ^1.1.0
  intl: ^0.19.0
  url_launcher: ^6.2.4
  flutter_launcher_icons: ^0.13.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"



flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/imageicons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900


    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf

